on:
  push:
    branches:
      - master
  release:
    types:
      - created
jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm install && npm install -g vsce
      - name: Run tests
        uses: GabrielBB/xvfb-action@v1.2
        with:
          run: npm test
      - name: Publish
        if: success() && matrix.os == 'ubuntu-latest'
        run: vsce package && vsce publish -p ${{ secrets.VSCE_PAT }}
# on:
#   push:
#     branches:
#       - master
#   release:
#     types:
#       - created
# jobs:
#   build:
#     strategy:
#       matrix:
#         os: [macos-latest, ubuntu-latest, windows-latest]
#     runs-on: ${{ matrix.os }}
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v2
#       - name: Install Node.js
#         uses: actions/setup-node@v1
#         with:
#           node-version: 10.x
#       - run: npm ci
#       - name: Run tests
#         uses: GabrielBB/xvfb-action@v1.2
#         with:
#           run: npm test
#       - name: Publish
#         if: success() && startsWith(github.ref, 'refs/tags/releases/') && matrix.os == 'ubuntu-latest'
#         run: npm run deploy
#         env:
#           VSCE_PAT: $
